"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TEMPLATES_DIR = '_templates_'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nb&o^u&*(%y+)%4rp@*s2p_esf5+%_w%wd_kp6^1$f*5y^%s!n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INBUILT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

PROJECT_APPS = [
    'chapter',
    'institute',
    'student',
    'teacher',
    'userprofile',
    'question',
    'paper',
    'answer',
    'approval',
    'attempt',
    'program',
]

EXTERNAL_APPS = [
    'imagekit',
    'storages',
]

INSTALLED_APPS = []
INSTALLED_APPS.extend(INBUILT_APPS)
INSTALLED_APPS.extend(PROJECT_APPS)
INSTALLED_APPS.extend(EXTERNAL_APPS)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, TEMPLATES_DIR)
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'portal.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '_staticroot_')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '_staticfiles_'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '_mediaroot_')

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
DEFAULT_FILE_STORAGE = 'portal.s3conf.MediaRootS3Boto3Storage'

DEFAULT_PROFILE_PICTURE_PATH = 'defaultprofilepicture.jpg'
DEFAULT_PROFILE_PICTURE_URL = STATIC_URL + DEFAULT_PROFILE_PICTURE_PATH

# SMTP Settings

EMAIL_HOST_USER = 'AKIAJAUMR2LEKFVMVZ7A'
EMAIL_HOST_PASSWORD = 'AlyceFn7Tu9NvL1XD3IJGdPEHF1OL0/dgzA5bOIf0ALk'
EMAIL_HOST = 'email-smtp.us-west-2.amazonaws.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_SUBJECT_PREFIX = "[Startup]"

SERVER_EMAIL = 'sahilkonkyana@gmail.com'
ADMINS = [
    ("Avinash", "avinashdec12@gmail.com"),
    ("Goutham", "gouthamarukonda@gmail.com"),
    ("Sahil", "sahilkonkyana@gmail.com"),
]

# S3 Settings

AWS_ACCESS_KEY_ID = "AKIAJCL63DMXW6K6MAAQ"
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = 'sk-portal-test'

AWS_DEFAULT_ACL = 'public-read'
AWS_QUERYSTRING_AUTH = False

AWS_AUTO_CREATE_BUCKET = True
AWS_S3_FILE_OVERWRITE = True
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
# AWS_S3_SIGNATURE_VERSION = 's3v4'
