
APPROVAL_NO_ACTION = '0'
APPROVAL_STUDENT_REGISTRATION = '1'
APPROVAL_TEACHER_REGISTRATION = '2'
APPROVAL_STUDENT_ADD_PROGRAM = '3'
APPROVAL_TEACHER_ADD_PROGRAM = '4'
APPROVAL_PASSWORD_RESET = '5'

APPROVAL_TYPES = (
	(APPROVAL_NO_ACTION, "No Action"),
	(APPROVAL_STUDENT_REGISTRATION, "Student Registration Approval"),
	(APPROVAL_TEACHER_REGISTRATION, "Teacher Registration Approval"),
	(APPROVAL_STUDENT_ADD_PROGRAM, "Student Program Registration Approval"),
	(APPROVAL_TEACHER_ADD_PROGRAM, "Teacher Program Registration Approval"),
	(APPROVAL_PASSWORD_RESET, "Password Reset Approval")
)
